services:
  postgres:
    image: postgres:latest
    container_name: projN3_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: projN3_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: ./flaskApp/Dockerfile
    container_name: projN3_web
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - app_network

  version: '3.8'

cloudbeaver:
  image: dbeaver/cloudbeaver:latest
  container_name: cloudbeaver
  ports:
    - "8978:8978"
  volumes:
    - cloudbeaver-data:/opt/cloudbeaver/workspace
  restart: always

volumes:
  cloudbeaver-data:
  postgres_data:

networks:
  app_network: